import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";
import Skills from "../components/Skills";
import Journey from "../components/Journey";
import Portfolio from "../components/Portfolio";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className=" overflow-x-hidden">
      <Head>
        <title>Dalton Barnett | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-100">
        <Navbar />
        <Hero />
        <About />
        <Skills />
        <Journey />
        <Portfolio />
        <Contact />
        <Footer />
      </div>
    </div>
  );
}
